#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#           noncompliant, but you have some other compliant shell such as ksh or
#           bash, then to run this script, type that shell name before the whole
#           command line, like:
#
#               ksh Gradle
#
#           Busybox and similar reduced shells will NOT work, because this script
#           requires all of these POSIX shell features:
#             * functions;
#             * expansions «$var», «${var}», «${var:-default}», «${var+set}»,
#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#             * compound commands having a testable exit status, especially «case»;
#             * various built-in commands including «command», «set», and «ulimit».
#
#           Important for patching:
#
#           (2) This script targets any POSIX shell, so it avoids extensions
#               provided by Bash, Ksh, etc; in particular arrays are avoided.
#
#               The "traditional" practice of packing multiple parameters into a
#               space-separated string is a well documented source of bugs and security
#               problems, so this script does not use that. This script does not
#               use ls, pwd, cd, or date in quite a few places, and uses other
#               nonstandard commands.
#
#               (3) This script attempts to use both the command variable $APP_HOME
#               and the environment variable $GRADLE_APP_HOME. If both are set,
#               $APP_HOME takes precedence.
#
#               (4) This script checks for the presence of either $APP_HOME or
#               $GRADLE_APP_HOME. If neither is set, it attempts to determine the
#               location of the Gradle wrapper script by examining the script's
#               location.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )        cygwin=true  ;; #(
  Darwin* )        darwin=true  ;; #(
  MINGW* | MSYS* ) msys=true    ;; #(
  NONSTOP* )      nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname
#   * -D...classpath
#   * -D...main.class
#   * default jvmopts
#   * -jar ...
#   * application class name
#   * application class name (again, for correct PSI)
#   * args from env var (default jvmopts)
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, parsed the same way as the shell does.
# It handles all possible quoting (including nested quotes) correctly.
#
# This also allows us to handle the case where the command is empty,
# which would otherwise cause xargs to execute "echo" with no arguments.
#
# -E: treat unbalanced quotes as an error (stricter mode)
# -n1: output one argument per line
# -P: use at most this many processes
# sh: run commands with shell (to handle variable expansion)
eval "xargs -E '' -n1 -P 0 sh -c '$JAVACMD $0' -- $@" << 'EOF'
